import type { Metadata } from "next";

import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import RainbowKitConfigProvider from "../components/RainbowKitConfigProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <RainbowKitConfigProvider>
          {children}
        </RainbowKitConfigProvider>
      </body>
    </html>
  );
}
